---
deployment:
  tasks:
    - export DEPLOYPATH=/home/princetonhosting/public_html/
    - /bin/cd _site
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R about $DEPLOYPATH
    - /bin/cp -R get_involved $DEPLOYPATH
    - /bin/cp -R announcements $DEPLOYPATH
    - /bin/cp -R events $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R sponsors $DEPLOYPATH
    - /bin/cp -R contact $DEPLOYPATH
    - /bin/cp -R officers $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
