# Site settings
title: Princeton ACM
email: ptonacm@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  The official website for the Princeton University
  student chapter of the Association for Computing Machinery.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://princetonacm.com" # the base hostname & protocol for your site
paginate: 5

# Build settings
markdown: kramdown