# Incorporated Jekyll Template
# Copyright 2013 Kippt, Inc.
# Licensed under MIT (https://github.com/kippt/jekyll-incorporated/blob/master/LICENSE)

# Blog Information
title:        "Princeton ACM"
subtitle:     "The official website for the Princeton University student chapter of the Association for Computing Machinery."
cover_image:  cover.jpg
logo:         logo.png

# Company information
company:      ACM Student Chapter of Princeton, Inc.
url:          http://princeton.acm.org/
facebook:     acmprinceton
github:       PrincetonACM
about_link:   /about/index.html
newsletter_link: http://eepurl.com/c3FpVf
signup_link: https://forms.gle/7HcG9zUtD7wPj9Rc9

# Analytics
analytics:
  google: true # Add tracking code in _includes/_google-analytics.html

# Google Fonts
# eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
google_font: 'Droid+Sans:400,700'

# Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://princeton.acm.org
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter:    pygments

permalink:     pretty
paginate_path: 'page:num'
paginate: 1

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  gzip: [ text/css, application/javascript ]
  debug: false

plugins: [jekyll-paginate]

plugins:
  - jemoji
  - jekyll-paginate
